// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1_DAL_DataAccessLayer.Context;

namespace _1_DAL_DataAccessLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211108155431_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.ChatLieu", b =>
                {
                    b.Property<Guid>("MaChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChatLieu1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ChatLieu");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChatLieu")
                        .HasName("PK__ChatLieu__453995BC55E5B565");

                    b.ToTable("ChatLieu");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.ChiTietSanPham", b =>
                {
                    b.Property<Guid>("MaCtsp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaCTSP");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<Guid?>("MaChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaClr")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaCLR");

                    b.Property<Guid?>("MaCo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaQr")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MaQR");

                    b.Property<Guid>("MaSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaSP");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCtsp")
                        .HasName("PK__ChiTietS__1E4FCECD9BEB1216");

                    b.HasIndex("MaChatLieu");

                    b.HasIndex("MaClr");

                    b.HasIndex("MaCo");

                    b.HasIndex("MaSize");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietSanPham");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.ChucVu", b =>
                {
                    b.Property<Guid>("MaChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChucVu")
                        .HasName("PK__ChucVu__D46395333CDE69D4");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.Color", b =>
                {
                    b.Property<Guid>("MaClr")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaCLR");

                    b.Property<string>("Color1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Color");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaClr")
                        .HasName("PK__Color__3DCE0379C5F9F66E");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.DanhMuc", b =>
                {
                    b.Property<Guid>("MaDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DanhMuc__B375088765BAB4C3");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.History", b =>
                {
                    b.Property<Guid>("MaHis")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaHIS");

                    b.Property<Guid?>("MaCtsp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaCTSP");

                    b.Property<Guid?>("MaNv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNV");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime");

                    b.HasKey("MaHis")
                        .HasName("PK__history__3C90C06949F39D52");

                    b.HasIndex("MaCtsp");

                    b.ToTable("history");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.HoaDon", b =>
                {
                    b.Property<Guid>("MaHd")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaHD");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("MaKh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaKH");

                    b.Property<Guid>("MaNv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNV");

                    b.Property<double?>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<double?>("TienNhan")
                        .HasColumnType("float");

                    b.Property<int>("TrangThaiHd")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiHD");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E0FE5F1EFC");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("MaHd")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaHD");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid?>("MaCtsp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaCTSP");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDonCh__2725A6E061AC8FD4");

                    b.HasIndex("MaCtsp");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.Image", b =>
                {
                    b.Property<Guid>("MaImage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Images")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("MaCtsp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaCTSP");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaImage")
                        .HasName("PK__Images__93330B7835DD95B7");

                    b.HasIndex("MaCtsp");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.KhachHang", b =>
                {
                    b.Property<Guid>("MaKh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaKH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E09566635");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.LoaiCoGiay", b =>
                {
                    b.Property<Guid>("MaCo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiCoGiay1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LoaiCoGiay");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaCo")
                        .HasName("PK__LoaiCoGi__27258E69B0EFA1FD");

                    b.ToTable("LoaiCoGiay");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.NhaCungCap", b =>
                {
                    b.Property<Guid>("MaNcc")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNCC");

                    b.Property<string>("CongTyCc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("congTyCC");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NguoiCc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NguoiCC");

                    b.Property<string>("Sdt")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("SDT");

                    b.HasKey("MaNcc")
                        .HasName("PK__NhaCungC__3A185DEB5433CF24");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.NhanVien", b =>
                {
                    b.Property<Guid>("MaNv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNV");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("MaChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("NamSinh")
                        .HasColumnType("int");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenNV");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A5238DEC2");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.SanPham", b =>
                {
                    b.Property<Guid>("MaSp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaSP");

                    b.Property<Guid?>("MaDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaNcc")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaNCC");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("TenSP");

                    b.Property<string>("ThuongHieu")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081CF11B9426");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaNcc");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.Size", b =>
                {
                    b.Property<Guid>("MaSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ChieuDaiChan")
                        .HasColumnType("float");

                    b.Property<int>("Size1")
                        .HasColumnType("int")
                        .HasColumnName("Size");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSize")
                        .HasName("PK__Size__A787E7EDA9C6C4A4");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("_1_DAL_DataAccessLayer.Models.ChatLieu", "MaChatLieuNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaChatLieu")
                        .HasConstraintName("FK__ChiTietSa__MaCha__3F466844");

                    b.HasOne("_1_DAL_DataAccessLayer.Models.Color", "MaClrNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaClr")
                        .HasConstraintName("FK__ChiTietSa__MaCLR__412EB0B6")
                        .IsRequired();

                    b.HasOne("_1_DAL_DataAccessLayer.Models.LoaiCoGiay", "MaCoNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaCo")
                        .HasConstraintName("FK__ChiTietSan__MaCo__3E52440B");

                    b.HasOne("_1_DAL_DataAccessLayer.Models.Size", "MaSizeNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaSize")
                        .HasConstraintName("FK__ChiTietSa__MaSiz__403A8C7D")
                        .IsRequired();

                    b.HasOne("_1_DAL_DataAccessLayer.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK__ChiTietSan__MaSP__4222D4EF")
                        .IsRequired();

                    b.Navigation("MaChatLieuNavigation");

                    b.Navigation("MaClrNavigation");

                    b.Navigation("MaCoNavigation");

                    b.Navigation("MaSizeNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.History", b =>
                {
                    b.HasOne("_1_DAL_DataAccessLayer.Models.ChiTietSanPham", "MaCtspNavigation")
                        .WithMany("Histories")
                        .HasForeignKey("MaCtsp")
                        .HasConstraintName("FK__history__MaCTSP__44FF419A");

                    b.Navigation("MaCtspNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.HoaDon", b =>
                {
                    b.HasOne("_1_DAL_DataAccessLayer.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__HoaDon__MaKH__2B3F6F97")
                        .IsRequired();

                    b.HasOne("_1_DAL_DataAccessLayer.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__HoaDon__MaNV__2C3393D0")
                        .IsRequired();

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("_1_DAL_DataAccessLayer.Models.ChiTietSanPham", "MaCtspNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaCtsp")
                        .HasConstraintName("FK__HoaDonChi__MaCTS__4AB81AF0");

                    b.HasOne("_1_DAL_DataAccessLayer.Models.HoaDon", "MaHdNavigation")
                        .WithOne("HoaDonChiTiet")
                        .HasForeignKey("_1_DAL_DataAccessLayer.Models.HoaDonChiTiet", "MaHd")
                        .HasConstraintName("FK__HoaDonChiT__MaHD__4BAC3F29")
                        .IsRequired();

                    b.Navigation("MaCtspNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.Image", b =>
                {
                    b.HasOne("_1_DAL_DataAccessLayer.Models.ChiTietSanPham", "MaCtspNavigation")
                        .WithMany("Images")
                        .HasForeignKey("MaCtsp")
                        .HasConstraintName("FK__Images__MaCTSP__47DBAE45");

                    b.Navigation("MaCtspNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.NhanVien", b =>
                {
                    b.HasOne("_1_DAL_DataAccessLayer.Models.ChucVu", "MaChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK__NhanVien__MaChuc__267ABA7A");

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.SanPham", b =>
                {
                    b.HasOne("_1_DAL_DataAccessLayer.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("FK__SanPham__MaDanhM__32E0915F");

                    b.HasOne("_1_DAL_DataAccessLayer.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK__SanPham__MaNCC__33D4B598");

                    b.Navigation("MaDanhMucNavigation");

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.ChatLieu", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.ChiTietSanPham", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.Color", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiet");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.LoaiCoGiay", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.NhaCungCap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("_1_DAL_DataAccessLayer.Models.Size", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
